        __asm__("MOV #0x0, W0"); //1bits change
        __asm__("MOV #0x0, W1"); //2bits change
        __asm__("MOV #0xFFF, W1"); //14bits change
        __asm__("MOV #0x1, W1"); //3bits change
        __asm__("MOV #0xFF, W15"); //13bits change
        __asm__("MOV #0x1, W3"); //4bits change
        __asm__("MOV #0x1, W7"); //5bits change
        __asm__("MOV #0x1, W15"); //6bits change
        __asm__("MOV #0xF, W3"); //7bits change
        __asm__("MOV #0xF, W7"); //8bits change
        __asm__("MOV #0xF, W15"); //9bits change
        __asm__("MOV #0x0, W0"); //1bits change
        __asm__("MOV #0x0, W1"); //2bits change
        __asm__("MOV #0xFF, W1"); //10bits change
        __asm__("MOV #0xFF, W3"); //11bits change
        __asm__("MOV #0xFFFF, W7"); //20bits change
        __asm__("MOV #0xFF, W7"); //12bits change
        __asm__("MOV #0x1, W1"); //3bits change
        __asm__("MOV #0x1, W3"); //4bits change
        __asm__("MOV #0xFFFF, W3"); //19bits change
        __asm__("MOV #0xFFFF, W15"); //21bits change
        __asm__("MOV #0xFFF, W3"); //15bits change
        __asm__("MOV #0xFFF, W7"); //16bits change
        __asm__("MOV #0xFFF, W15"); //17bits change
        __asm__("MOV #0xFFFF, W1"); //18bits change